### ISSUE TITLE
Highlink Cleaned Links

### ISSUE THREAD

**Issue by ldgbc** [tumpio/requestcontrol#1]
Thank you for making this add-on. Currently I'm using Clean Links but from the look of the support for e10s (Firefox) will be far away.

I only briefly tested this addon and it seem to be working so far with e10s enable.

The only issue I'm currently find this Add-on/Extension lacking is "visibility". With other add-on, usually link that got "clean" get highlight in a colors so it indicate visually.

With JustRedirect, I've no idea if it work or not. It would be good if "highlighting" feature is added or someway to indicate the link you just click was "cleaned".

Thank you.

**Comment by tumpio** [comment]
Yes, definitively there should be some user feedback. Highlighting a link is not an option because the "cleaning" is done on request level. 

The feedback could be a toolbar button with a changing status icon (grey | green) with some info tooltip displaying the recently "cleaned" requests. I have to check what kind of feedback possibilities are available in WebExtensions.

I'm currently working on the options view, I'm trying to make the rule definition more user friendly. I've some other ideas too, like adding different request types (images, scripts, main frame,...) and rule actions (block, clean, redirect to). Stay tuned :)

**Comment by tumpio** [comment]
In the new release there is now a status icon in navigation bar showing the state of the request action taken. I also finished the options update and rule actions support.
