### ISSUE TITLE
Regular expressions in path pattern work only in test, not in production

### ISSUE THREAD

**Issue by justa9** [tumpio/requestcontrol#113]
### Expected behavior
A regular expression in a path pattern should work in "production".

### Actual behavior
A regular expression in a path pattern should works only in "test".

### Steps to reproduce the problem
* Create a new rule for a hostname (i.e. example.com)
* Add a regular expression in the path field (i.e. [a-z]*)
* Create a redirect rule (as a showcase), select it and click on "Test selected".
* Type in a URL (i.e. http://example.com/something) and verify that the matching works
* However if you visit the above URL, no redirection occurs.

This seems to me like regular expressions are recognised only in "testing", but not in "production". In the latter case, one could still use "*" but that seems to be very limiting and does not cover all cases.

Thank you.

**Comment by geekyi** [comment]
Can confirm.

I tried to debug the addon and verified that the filter pattern "*://example.com/[a-z]*" is actually set.

I think the root cause is that [Match patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns) aren't exactly the same as regular expressions (more like glob patterns rather). Don't think there's an easier solution for this.

**Comment by tumpio** [comment]
Only "*" wildcard is allowed in path, see manual. You can use **Includes** and **Excludes** in extra url mathers to match requests using regular expression. They work on top of the match patterns.

Fixed the rule tester to escape regexp chars properly.
