### ISSUE TITLE
where is the Secure rule?

### ISSUE THREAD

**Issue by practik** [tumpio/requestcontrol#114]
Hi tumpio, I just updated from 1.14.0 to 1.15.1 (nice icon!). I read in the release notes that RC now includes a new Secure rule to upgrade HTTP requests to HTTPS, but when I checked my rules I couldn't find it. Is it not user-configurable?

I'm asking because I already use [HTTPZ](https://github.com/claustromaniac/httpz) for the same purpose. If RC now duplicates that functionality, I would be able to uninstall HTTPZ – but only if I can whitelist a couple of hostnames that should not be upgraded to HTTPS.

**Comment by geeknik** [comment]
You have to create a new rule. Look under action where it says Secure: 
![Screenshot_2020-03-13_12-26-54](https://user-images.githubusercontent.com/466878/76644966-f0808e00-654f-11ea-87bf-7579c63ee326.png)

**Comment by practik** [comment]
Aha!  Thanks, geeknik – I'm on it!

**Comment by tumpio** [comment]
Yes, only a new action called "Secure" was added. It should be used instead of the redirect action to upgrade http requests to https. It sets the "upgradeToSecure" flag that tells Firefox to handle the upgrade internally (without being blocked by CORS checks). https://bugzilla.mozilla.org/show_bug.cgi?id=1149250

It likely conflicts with other add-ons that tries to modify the same request with redirection.

**Comment by practik** [comment]
Thanks, tumpio. I can confirm that it definitely conflicts with HTTPZ – just for fun I tested, and the result was endless redirection loops. But I would guess that anyone who's comfortable using RC would not run both extensions at the same time.
