### ISSUE TITLE
Action "Secure" improvement request

### ISSUE THREAD

**Issue by crssi** [tumpio/requestcontrol#120]
Is it possible to make failback to HTTP option, when using `Secure` action in case when the resource is not accesible over HTTPS?

Thank you and cheers

**Comment by geekyi** [comment]
FYI, I've been using this even before "secure" actions were introduced, with a "redirect" action in this addon, and with [smart https](https://mybrowseraddon.com/smart-https.html) to achieve for the specific feature. 

Ocassionally, I may want to force enable it globally for testing, or to specific types of scenarios, so that's when I use requestcontrol(e.g. when website owners have misconfigured urls). In most of these cases optional fallback doesn't work since it's wrong in the first place..

Do you have any specific usecases that isn't covered by smarthttps?

**Comment by geeknik** [comment]
> Do you have any specific usecases that isn't covered by smarthttps?

Not having to install multiple extensions to do the same job is a very specific use case I'm interested in.

**Comment by tumpio** [comment]
I added the Secure action, because I know some users may use the redirect action for upgrading http to https. Secure action should be used instead to let browser handle the upgrade correctly and not be blocked by CORS checks. Making it smarter by fall-back etc. might be quite much work. Don't expect it to be added any time soon if ever.

**Comment by crssi** [comment]
I think so too now. Soon almost everything will go secure, so no point to loose time on this one.
