### ISSUE TITLE
Request Control can't be install with CyberFox

### ISSUE THREAD

**Issue by WagnerGMD** [tumpio/requestcontrol#2]
Hello,

I just want to report that I had met one trouble to install (the addon) [Request Control](https://addons.mozilla.org/en-US/firefox/addon/requestcontrol/) (v1.2.2)... Then, I had discover a few topics on the CyberFox Forum (like [this one](https://8pecxstudios.com/Forums/viewtopic.php?t=1663)). To resume, apparently, for the browser the file (archive .xpi) is corrupted... and perhaps there's one solution which consist to modify the file **manifest.json** but after three attempts, it doesn't seem to work... and no, sorry I don't have any idea to fix the trouble.

And thank you for Request Control because it seem's to work fine with Firefox.  Indeed, I was looking for one solution to avoid the redirect link (via the adress  "outgoing.prod.mozaws.net") on the [Mozilla Addon website.](https://addons.mozilla.org)

I hope you will find one way to fix the trouble about Cyberfox (x64_v50.1.0).
Kind regards.

**Comment by tumpio** [comment]
Hi Wagner and thank you for your report.

Request Control is a **Firefox** add-on. it is my first add-on build with the new WebExtension add-on framework that Firefox is moving to. In theory it would be a "cross-browser" extension since WebExtensions are supported by all the main stream browsers Chrome, Opera and Edge. But in practice it most likely works only in Firefox at the moment.

I checked that forum link which you shared. According to the Mozilla Developer Network, the applications key is not required anymore in Firefox since version 48 and the key is not supported by Blink-based browsers (Google Chrome and Opera). Is Cyberfox a custom build of Firefox with its own manifest.json requirements for WebExtensions? From the MDN documentation I get the idea that requiring application keys is not wanted for the standard of WebExtensions. Requiring a single browser specific manifest key entry is not very cross-browser friendly. :)

**Comment by tumpio** [comment]
I'm not going to bother with this. CyberFox should use the latest Firefox code base. The developer of Cyberfox states that 

> For cyberfox 51.* branch its not needed.

Update to Cyberfox version 51 which must use at least version 48 code branch of Firefox or something..

**Comment by WagnerGMD** [comment]
Hello,

I understand even if I was a little deceive by the answer but now, the trouble is gone. In fact, it was fixed via the previous version; the last one published several days just before the CyberFox_v51.
So, I had finally decide to reply just to confirm it and to let you know.
Kind regards.
