### ISSUE TITLE
Chrome / Opera / Vivaldi compatibility?

### ISSUE THREAD

**Issue by EC-O-DE** [tumpio/requestcontrol#37]
### Expected behavior
WebExtensions all work in Chrome, Opera and Vivaldi (+Yandex) and it's nice to get Firefox along!

### Actual behavior
Extensions marked for Firefox (?) only (?)
### Steps to reproduce the problem
* https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension
* Test with Chrome, opera, Vivaldi
* Iron out mishaps

**Comment by tumpio** [comment]
Well, it should be easy if they are truly cross-platform. But this is my first webextension and it is specifically made for Firefox. I have no experience of webextension on other browser platforms so I don't know the differences between them. Other than differences between supported APIs. And I'm not personally that much interested about supporting other browsers since I don't use them..

**Comment by ZenFi** [comment]
Fair enough.

I'll test this at some point. 

Looking very interesting.

**Comment by EC-O-DE** [comment]
hmm
