### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [tumpio/requestcontrol#43]
Hey @tumpio : )

One thing I am in the process of doing with the ghacks user.js [wiki page for extensions](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-B:-Extensions) is to add **Privacy Policy** links (like below). If an extension has one that respects privacy, awesome, if not, no such "badge" (and if it has one one that stinks, it will not be recommended). 

Would you consider creating a simple Privacy Policy wiki page or root md file? Cheers

* [uBlock Origin](https://addons.mozilla.org/firefox/addon/ublock-origin/) <sup>✔ [Privacy](https://github.com/gorhill/uBlock/wiki/Privacy-policy)</sup> | [GitHub](https://github.com/gorhill/uBlock)

Edit: or you can just add it to AMO (not sure how you apply that per release)

* [Decentraleyes](https://addons.mozilla.org/firefox/addon/decentraleyes/) <sup>✔ [Privacy](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/privacy/)</sup> | [GitHub](https://github.com/Synzvato/decentraleyes)  << AMO example

**Comment by Atavic** [comment]
Both GH and AMO have it: released under Mozilla Public License, version 2.0

**Comment by tumpio** [comment]
@Thorin-Oakenpants I don't have any official policy for user's privacy and haven't thought about needing one. I respect the privacy of users (one of the main reasons for me sharing this add-on). I also follow the principles of the Mozilla Manifesto:
https://www.mozilla.org/en-US/about/manifesto/#principle-04

But I don't take any liability for privacy violations that could be for example caused by the misuse of the add-on.
