### ISSUE TITLE
SIMPLE QUESTIONS

### ISSUE THREAD

**Issue by Decopi** [tumpio/requestcontrol#60]
Hi,

I was using two add-ons for blocking track/skip links (NeatUrl and SkipRedirect).

I read many good recommendations about RequestControl, so now I am testing it. My simple questions are:

1) Is RequestControl working automatically for any web-address? Or do I need to manually set every link?

2) Is RequestControl blocking both track and skip links? May I replace my previous 2 add-ons (SkipRedirect and NeatUrl) with RequestControl?

Thank you!

[https://addons.mozilla.org/en-US/firefox/addon/skip-redirect/](url)

[https://addons.mozilla.org/en-US/firefox/addon/neat-url/](url)

**Comment by crssi** [comment]
Despite the RequestControl extension is very good I don't use it, since it lacks one crucial element.
That is option to not interfere when followed link is on the same domain or subdomain.
This is not easy task to implement, but Skip Redirect author has implemented by my suggestion, see https://github.com/sblask/webextension-skip-redirect/issues/29 followed with https://github.com/sblask/webextension-skip-redirect/issues/30
That is why RequestControl is inferior to the Skip Redirect and can never replace it.
Here you can also find some nice info: https://github.com/ghacksuserjs/ghacks-user.js/issues/149
Some more config for NeatURL you can find here https://github.com/Smile4ever/firefoxaddons/issues/112

I would be happy to give RC second chance when/if this is implemented.

Cheers

**Comment by Decopi** [comment]
Hi @crssi , thanks a lot for your useful answer. Please, allow me some questions:

1) What about performance (speed, RAM, CPU)? Is RequestControl more efficient than two separate add-ons?

2) I found your NeatUrl config extremely useful! Thank you!
Do you have something similar for SkipRedirect?

PS: I am testing the 3 add-ons (RequestControl, NeatUrl, SkipRedirect) in 3 separate browsers (Firefox). At first sight, RequestControl cough more stuff. Sadly I have not tech background to understand if it is good/bad (that is the reason I posted my questions here).
I also am aware that settings/config might make all the difference (and that is why your NeatUrl config was so useful to me... hope you have something similar for SkipRedirect).

**Comment by crssi** [comment]
I never tested performance, since my browsing experience is OK.
But if you would like to test performance, you ca do it with [Gecko Profiler](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler)
I have some additions to SR, but I have already unfair feeling of hijacking this one.

Cheers

**Comment by Decopi** [comment]
Please @crssi , reconsider the possibility of sharing with me your SR' config, exclusively just for my tests purpose.
Thank you again in advance!

**Comment by crssi** [comment]
All default + additions to black list.
```
/_login
/adfs/ls/
/sso/
/saml/
rover.ebay.co
/openid/
microsofttranslator.com/
translate.google.com/
youtube.com/embed/
t.umblr.com/redirect
chart.googleapis.com/chart
/wsfederation
medium.com/
archive.org/
```
Cheers

**Comment by tumpio** [comment]
> 1.   Is RequestControl working automatically for any web-address? Or do I need to manually set every link?

Not by default. You would need to create a global rule for it.

 > 2.   Is RequestControl blocking both track and skip links?  May I replace my previous 2 add-ons (SkipRedirect and NeatUrl) with RequestControl?

You can both block tracking requests and skip redirect requests with Request Control with user defined rules for it.
